// eta_icons Dart 常量生成器：读取 src/registry.json → 输出 lib/eta/icon/eta_icons.dart
// 用法：node app/eta-tools/eta_icons/3_gen_dart.mjs [outDart]
import fs from 'node:fs';
import path from 'node:path';

const HERE = import.meta.dirname;
const APP = path.resolve(HERE, '../..');       // eta_icons → eta-tools → app/
const registry = JSON.parse(fs.readFileSync(path.join(HERE, 'src', 'registry.json'), 'utf8'));
const OUT = process.argv[2] ?? path.join(APP, 'lib', 'eta', 'icon', 'eta_icons.dart');

const lines = [];
lines.push('// AUTO-GENERATED by app/eta-tools/eta_icons/3_gen_dart.mjs — 请勿手改。');
lines.push('//');
lines.push('// eta.icon 图标引用归一化入口：项目内所有图标统一走本类常量，');
lines.push('// 不再直接引用 Flutter Material Icons.*。');
lines.push('//');
lines.push('// 字形体系（自建 icon font，来源 mingcute icons Apache-2.0 + Tabler MIT，见 app/eta-tools/eta_icons/）：');
lines.push('//   - 裸名如 EtaIcons.play        → 实心(filled) 视觉');
lines.push('//   - Outline 尾缀如 EtaIcons.playOutline → 描边(regular) 视觉');
lines.push('// 字体文件：assets/fonts/EtaIcons.ttf（单字体族、描边/实心双 codepoint 区段）。');
lines.push('//');
lines.push("import 'package:flutter/widgets.dart';");
lines.push('');
lines.push('/// 项目统一图标（eta.icon 体系）。');
lines.push('abstract final class EtaIcons {');
lines.push("  static const String _family = 'EtaIcons';");
lines.push('');
lines.push('  EtaIcons._();');
lines.push('');

// const 名可能首字母大写/含特殊字符，需 sanitize 成合法 Dart 标识符（registry 已保证唯一）
for (const [name, g] of Object.entries(registry.glyphs).sort((a, b) => a[1].codepoint - b[1].codepoint)) {
  const hex = `0x${g.codepoint.toString(16).padStart(4, '0').toUpperCase()}`;
  lines.push(`  /// ${g.materials.join(' / ')} (${g.style === 'filled' ? '实心' : '描边'})`);
  lines.push(`  static const IconData ${name} = IconData(${hex}, fontFamily: _family);`);
  lines.push('');
}
lines.push('}');
lines.push('');

fs.writeFileSync(OUT, lines.join('\n'), 'utf8');
console.log('wrote', OUT, 'constants:', Object.keys(registry.glyphs).length);
