// AUTO-GENERATED by app/eta-tools/eta_icons/3_gen_dart.mjs — 请勿手改。
//
// eta.icon 图标引用归一化入口：项目内所有图标统一走本类常量，
// 不再直接引用 Flutter Material Icons.*。
//
// 字形体系（自建 icon font，来源 mingcute icons Apache-2.0 + Tabler MIT，见 app/eta-tools/eta_icons/）：
//   - 裸名如 EtaIcons.play        → 实心(filled) 视觉
//   - Outline 尾缀如 EtaIcons.playOutline → 描边(regular) 视觉
// 字体文件：assets/fonts/EtaIcons.ttf（单字体族、描边/实心双 codepoint 区段）。
//
import 'package:flutter/widgets.dart';

/// 项目统一图标（eta.icon 体系）。
abstract final class EtaIcons {
  static const String _family = 'EtaIcons';

  EtaIcons._();

  /// abc (描边)
  static const IconData abcOutline = IconData(0xE100, fontFamily: _family);

  /// center_focus_strong_outlined / gps_fixed_outlined / my_location_outlined (描边)
  static const IconData aimingOutline = IconData(0xE103, fontFamily: _family);

  /// photo_library_outlined (描边)
  static const IconData album2Outline = IconData(0xE104, fontFamily: _family);

  /// album_outlined (描边)
  static const IconData albumOutline = IconData(0xE105, fontFamily: _family);

  /// error_outline (描边)
  static const IconData alertOutline = IconData(0xE107, fontFamily: _family);

  /// bedtime_off_outlined (描边)
  static const IconData bedtimeOffOutline = IconData(0xE10B, fontFamily: _family);

  /// blur_on_outlined (描边)
  static const IconData blurOnOutline = IconData(0xE10D, fontFamily: _family);

  /// menu_book_outlined (描边)
  static const IconData bookOutline = IconData(0xE10F, fontFamily: _family);

  /// brightness_auto_outlined (描边)
  static const IconData brightnessOutline = IconData(0xE111, fontFamily: _family);

  /// cleaning_services_outlined (描边)
  static const IconData broomOutline = IconData(0xE112, fontFamily: _family);

  /// location_city_outlined (描边)
  static const IconData buildingOutline = IconData(0xE113, fontFamily: _family);

  /// bar_chart_outlined (描边)
  static const IconData chartBarOutline = IconData(0xE115, fontFamily: _family);

  /// data_usage_outlined / pie_chart_outline (描边)
  static const IconData chartPieOutline = IconData(0xE117, fontFamily: _family);

  /// analytics_outlined / leaderboard_outlined (描边)
  static const IconData chartVerticalOutline = IconData(0xE118, fontFamily: _family);

  /// chat_bubble_outline (描边)
  static const IconData chatOutline = IconData(0xE119, fontFamily: _family);

  /// check_circle_outline (描边)
  static const IconData checkCircleOutline = IconData(0xE11C, fontFamily: _family);

  /// memory_outlined (描边)
  static const IconData chipOutline = IconData(0xE11D, fontFamily: _family);

  /// cancel_outlined (描边)
  static const IconData closeCircleOutline = IconData(0xE121, fontFamily: _family);

  /// cloud_off_outlined / cloud_outlined (描边)
  static const IconData cloudOutline = IconData(0xE123, fontFamily: _family);

  /// view_column_outlined (描边)
  static const IconData columnsOutline = IconData(0xE125, fontFamily: _family);

  /// mode_comment_outlined (描边)
  static const IconData commentOutline = IconData(0xE126, fontFamily: _family);

  /// speed_outlined (描边)
  static const IconData dashboard4Outline = IconData(0xE12A, fontFamily: _family);

  /// delete_outline / delete_sweep_outlined (描边)
  static const IconData deleteOutline = IconData(0xE12C, fontFamily: _family);

  /// deselect (描边)
  static const IconData deselectOutline = IconData(0xE12D, fontFamily: _family);

  /// devices_outlined (描边)
  static const IconData deviceOutline = IconData(0xE12E, fontFamily: _family);

  /// text_snippet_outlined (描边)
  static const IconData docmentOutline = IconData(0xE12F, fontFamily: _family);

  /// blur_circular_outlined (描边)
  static const IconData dotCircleOutline = IconData(0xE131, fontFamily: _family);

  /// download_outlined (描边)
  static const IconData downloadOutline = IconData(0xE136, fontFamily: _family);

  /// edit_outlined (描边)
  static const IconData editOutline = IconData(0xE13A, fontFamily: _family);

  /// exit_to_app_outlined (描边)
  static const IconData exitOutline = IconData(0xE13D, fontFamily: _family);

  /// visibility_off_outlined (描边)
  static const IconData eyeCloseOutline = IconData(0xE13E, fontFamily: _family);

  /// visibility_outlined (描边)
  static const IconData eyeOutline = IconData(0xE13F, fontFamily: _family);

  /// drive_file_move_outlined (描边)
  static const IconData fileImportOutline = IconData(0xE140, fontFamily: _family);

  /// lyrics_outlined (描边)
  static const IconData fileMusicOutline = IconData(0xE142, fontFamily: _family);

  /// insert_drive_file_outlined (描边)
  static const IconData fileOutline = IconData(0xE143, fontFamily: _family);

  /// fingerprint_outlined (描边)
  static const IconData fingerprintOutline = IconData(0xE146, fontFamily: _family);

  /// local_fire_department_outlined (描边)
  static const IconData fireOutline = IconData(0xE147, fontFamily: _family);

  /// healing_outlined (描边)
  static const IconData firstAidKitOutline = IconData(0xE148, fontFamily: _family);

  /// bolt_outlined (描边)
  static const IconData flashOutline = IconData(0xE14A, fontFamily: _family);

  /// science_outlined (描边)
  static const IconData flaskOutline = IconData(0xE14B, fontFamily: _family);

  /// folder_open_outlined (描边)
  static const IconData folderOpenOutline = IconData(0xE14F, fontFamily: _family);

  /// folder_outlined (描边)
  static const IconData folderOutline = IconData(0xE150, fontFamily: _family);

  /// folder_copy_outlined (描边)
  static const IconData foldersOutline = IconData(0xE151, fontFamily: _family);

  /// font_download_outlined (描边)
  static const IconData fontOutline = IconData(0xE152, fontFamily: _family);

  /// text_fields_outlined (描边)
  static const IconData fontSizeOutline = IconData(0xE154, fontFamily: _family);

  /// zoom_out_map_outlined (描边)
  static const IconData fullscreenExit2Outline = IconData(0xE157, fontFamily: _family);

  /// numbers_outlined (描边)
  static const IconData hashtagOutline = IconData(0xE158, fontFamily: _family);

  /// headphones_outlined (描边)
  static const IconData headphoneOutline = IconData(0xE159, fontFamily: _family);

  /// favorite_border / favorite_outline (描边)
  static const IconData heartOutline = IconData(0xE15B, fontFamily: _family);

  /// monitor_heart_outlined (描边)
  static const IconData heartbeatOutline = IconData(0xE15C, fontFamily: _family);

  /// high_quality_outlined (描边)
  static const IconData highQualityOutline = IconData(0xE15D, fontFamily: _family);

  /// history_outlined (描边)
  static const IconData historyOutline = IconData(0xE15F, fontFamily: _family);

  /// home_outlined (描边)
  static const IconData homeOutline = IconData(0xE161, fontFamily: _family);

  /// info_outline (描边)
  static const IconData informationOutline = IconData(0xE162, fontFamily: _family);

  /// key_outlined / password_outlined / vpn_key_outlined (描边)
  static const IconData keyOutline = IconData(0xE163, fontFamily: _family);

  /// energy_savings_leaf_outlined (描边)
  static const IconData leafOutline = IconData(0xE165, fontFamily: _family);

  /// checklist_outlined (描边)
  static const IconData listCheck3Outline = IconData(0xE16A, fontFamily: _family);

  /// lock_outline / sync_lock_outlined (描边)
  static const IconData lockOutline = IconData(0xE16B, fontFamily: _family);

  /// animation_outlined / auto_fix_normal_outlined (描边)
  static const IconData magic2Outline = IconData(0xE16D, fontFamily: _family);

  /// auto_fix_high_outlined (描边)
  static const IconData magic3Outline = IconData(0xE16F, fontFamily: _family);

  /// workspace_premium_outlined (描边)
  static const IconData medalOutline = IconData(0xE170, fontFamily: _family);

  /// view_stream_outlined (描边)
  static const IconData menuOutline = IconData(0xE172, fontFamily: _family);

  /// forum_outlined (描边)
  static const IconData messageOutline = IconData(0xE173, fontFamily: _family);

  /// mic_external_on_outlined (描边)
  static const IconData micOutline = IconData(0xE175, fontFamily: _family);

  /// (extra:miniplayer) (描边)
  static const IconData miniplayerOutline = IconData(0xE177, fontFamily: _family);

  /// desktop_windows_outlined (描边)
  static const IconData monitorOutline = IconData(0xE178, fontFamily: _family);

  /// dark_mode_outlined (描边)
  static const IconData moonOutline = IconData(0xE179, fontFamily: _family);

  /// bedtime_outlined (描边)
  static const IconData moonStarsOutline = IconData(0xE17B, fontFamily: _family);

  /// library_music_outlined (描边)
  static const IconData music2Outline = IconData(0xE17F, fontFamily: _family);

  /// audiotrack_outlined / music_note_outlined / notes_outlined (描边)
  static const IconData musicOutline = IconData(0xE180, fontFamily: _family);

  /// create_new_folder_outlined (描边)
  static const IconData newFolderOutline = IconData(0xE181, fontFamily: _family);

  /// color_lens_outlined (描边)
  static const IconData palette2Outline = IconData(0xE182, fontFamily: _family);

  /// palette_outlined (描边)
  static const IconData paletteOutline = IconData(0xE183, fontFamily: _family);

  /// pause_circle_outline (描边)
  static const IconData pauseCircleOutline = IconData(0xE186, fontFamily: _family);

  /// call_outlined (描边)
  static const IconData phoneCallOutline = IconData(0xE187, fontFamily: _family);

  /// broken_image_outlined (描边)
  static const IconData pic2Outline = IconData(0xE188, fontFamily: _family);

  /// image_outlined / wallpaper_outlined (描边)
  static const IconData picOutline = IconData(0xE189, fontFamily: _family);

  /// offline_pin_outlined (描边)
  static const IconData pinOutline = IconData(0xE18B, fontFamily: _family);

  /// play_circle_outline (描边)
  static const IconData playCircleOutline = IconData(0xE18E, fontFamily: _family);

  /// queue_music_outlined (描边)
  static const IconData playlistOutline = IconData(0xE190, fontFamily: _family);

  /// extension_outlined (描边)
  static const IconData pluginOutline = IconData(0xE191, fontFamily: _family);

  /// power_settings_new_outlined (描边)
  static const IconData powerOutline = IconData(0xE192, fontFamily: _family);

  /// published_with_changes_outlined (描边)
  static const IconData publishedWithChangesOutline = IconData(0xE193, fontFamily: _family);

  /// refresh_outlined (描边)
  static const IconData refreshOutline = IconData(0xE197, fontFamily: _family);

  /// circle_outlined (描边)
  static const IconData roundOutline = IconData(0xE19B, fontFamily: _family);

  /// verified_outlined (描边)
  static const IconData safetyCertificateOutline = IconData(0xE19C, fontFamily: _family);

  /// memory_stick (描边)
  static const IconData memoryStickOutline = IconData(0xE1A0, fontFamily: _family);

  /// manage_search_outlined (描边)
  static const IconData search3Outline = IconData(0xE1A1, fontFamily: _family);

  /// dns_outlined (描边)
  static const IconData serverOutline = IconData(0xE1A4, fontFamily: _family);

  /// settings_outlined (描边)
  static const IconData settingsOutline = IconData(0xE1A5, fontFamily: _family);

  /// mobile_screen_share_outlined (描边)
  static const IconData shareForwardOutline = IconData(0xE1A6, fontFamily: _family);

  /// gpp_bad_outlined / security_outlined / shield_outlined (描边)
  static const IconData shieldOutline = IconData(0xE1A7, fontFamily: _family);

  /// account_tree_outlined (描边)
  static const IconData sitemapOutline = IconData(0xE1A9, fontFamily: _family);

  /// skip_next_outlined (描边)
  static const IconData skipForwardOutline = IconData(0xE1AB, fontFamily: _family);

  /// graphic_eq_outlined (描边)
  static const IconData soundLineOutline = IconData(0xE1AF, fontFamily: _family);

  /// speaker_outlined (描边)
  static const IconData speakerOutline = IconData(0xE1B2, fontFamily: _family);

  /// star_outline (描边)
  static const IconData starOutline = IconData(0xE1B5, fontFamily: _family);

  /// av_timer_outlined (描边)
  static const IconData stopwatchOutline = IconData(0xE1B7, fontFamily: _family);

  /// sd_storage_outlined / storage_outlined (描边)
  static const IconData storageOutline = IconData(0xE1B8, fontFamily: _family);

  /// storefront_outlined (描边)
  static const IconData storeOutline = IconData(0xE1B9, fontFamily: _family);

  /// subtitles_off_outlined / subtitles_outlined (描边)
  static const IconData subtitleOutline = IconData(0xE1BB, fontFamily: _family);

  /// light_mode_outlined / wb_sunny_outlined (描边)
  static const IconData sunOutline = IconData(0xE1BD, fontFamily: _family);

  /// thumb_up_alt_outlined (描边)
  static const IconData thumbUpOutline = IconData(0xE1BE, fontFamily: _family);

  /// tonality_outlined (描边)
  static const IconData tonalityOutline = IconData(0xE1C0, fontFamily: _family);

  /// engineering_outlined (描边)
  static const IconData toolOutline = IconData(0xE1C1, fontFamily: _family);

  /// compare_arrows_outlined (描边)
  static const IconData transferVerticalOutline = IconData(0xE1C4, fontFamily: _family);

  /// language_outlined / translate_outlined (描边)
  static const IconData translateOutline = IconData(0xE1C6, fontFamily: _family);

  /// link_off_outlined (描边)
  static const IconData unlinkOutline = IconData(0xE1C8, fontFamily: _family);

  /// lock_open_outlined (描边)
  static const IconData unlockOutline = IconData(0xE1C9, fontFamily: _family);

  /// account_circle_outlined / person_outline (描边)
  static const IconData userOutline = IconData(0xE1CC, fontFamily: _family);

  /// music_off_outlined (描边)
  static const IconData volumeOffOutline = IconData(0xE1D0, fontFamily: _family);

  /// sync_problem_outlined / warning_amber_outlined (描边)
  static const IconData warningOutline = IconData(0xE1D2, fontFamily: _family);

  /// delete_forever_outlined (描边)
  static const IconData wastebasketOutline = IconData(0xE1D3, fontFamily: _family);

  /// add (实心)
  static const IconData add = IconData(0xE701, fontFamily: _family);

  /// my_location (实心)
  static const IconData aiming = IconData(0xE702, fontFamily: _family);

  /// error (实心)
  static const IconData alert = IconData(0xE706, fontFamily: _family);

  /// arrow_back (实心)
  static const IconData arrowLeft = IconData(0xE708, fontFamily: _family);

  /// arrow_right_alt (实心)
  static const IconData arrowRight = IconData(0xE709, fontFamily: _family);

  /// flaky (实心)
  static const IconData asterisk = IconData(0xE70A, fontFamily: _family);

  /// bluetooth_audio (实心)
  static const IconData bluetooth = IconData(0xE70C, fontFamily: _family);

  /// menu_book (实心)
  static const IconData book = IconData(0xE70E, fontFamily: _family);

  /// rounded_corner (实心)
  static const IconData borderRadius = IconData(0xE710, fontFamily: _family);

  /// bar_chart (实心)
  static const IconData chartBar = IconData(0xE714, fontFamily: _family);

  /// multiline_chart (实心)
  static const IconData chartLine = IconData(0xE716, fontFamily: _family);

  /// check (实心)
  static const IconData check = IconData(0xE71A, fontFamily: _family);

  /// check_circle (实心)
  static const IconData checkCircle = IconData(0xE71B, fontFamily: _family);

  /// radio_button_off (实心)
  static const IconData circleDash = IconData(0xE71E, fontFamily: _family);

  /// schedule (实心)
  static const IconData clock = IconData(0xE71F, fontFamily: _family);

  /// close (实心)
  static const IconData close = IconData(0xE720, fontFamily: _family);

  /// cloud / cloud_queue / wb_cloudy (实心)
  static const IconData cloud = IconData(0xE722, fontFamily: _family);

  /// colorize (实心)
  static const IconData colorPicker = IconData(0xE724, fontFamily: _family);

  /// keyboard_return (实心)
  static const IconData cornerDownLeft = IconData(0xE727, fontFamily: _family);

  /// north_west (实心)
  static const IconData cornerUpLeft = IconData(0xE728, fontFamily: _family);

  /// speed (实心)
  static const IconData dashboard3 = IconData(0xE729, fontFamily: _family);

  /// delete (实心)
  static const IconData delete = IconData(0xE72B, fontFamily: _family);

  /// radio_button_checked (实心)
  static const IconData dotCircle = IconData(0xE730, fontFamily: _family);

  /// more_horiz (实心)
  static const IconData dots = IconData(0xE732, fontFamily: _family);

  /// drag_indicator / more_vert (实心)
  static const IconData dotsVertical = IconData(0xE733, fontFamily: _family);

  /// arrow_drop_down / expand_more / keyboard_arrow_down (实心)
  static const IconData downSmall = IconData(0xE734, fontFamily: _family);

  /// download / downloading (实心)
  static const IconData download = IconData(0xE735, fontFamily: _family);

  /// grain (实心)
  static const IconData drizzle = IconData(0xE737, fontFamily: _family);

  /// opacity / water_drop (实心)
  static const IconData drop = IconData(0xE738, fontFamily: _family);

  /// public / travel_explore (实心)
  static const IconData earth = IconData(0xE739, fontFamily: _family);

  /// login (实心)
  static const IconData entrance = IconData(0xE73B, fontFamily: _family);

  /// logout (实心)
  static const IconData exit = IconData(0xE73C, fontFamily: _family);

  /// lyrics (实心)
  static const IconData fileMusic = IconData(0xE741, fontFamily: _family);

  /// tune (实心)
  static const IconData filter = IconData(0xE744, fontFamily: _family);

  /// fingerprint (实心)
  static const IconData fingerprint = IconData(0xE745, fontFamily: _family);

  /// bolt (实心)
  static const IconData flash = IconData(0xE749, fontFamily: _family);

  /// flip (实心)
  static const IconData flipHorizontal = IconData(0xE74C, fontFamily: _family);

  /// foggy (实心)
  static const IconData fog = IconData(0xE74D, fontFamily: _family);

  /// folder_open (实心)
  static const IconData folderOpen = IconData(0xE74E, fontFamily: _family);

  /// format_size (实心)
  static const IconData fontSize = IconData(0xE753, fontFamily: _family);

  /// fullscreen (实心)
  static const IconData fullscreen = IconData(0xE755, fontFamily: _family);

  /// fullscreen_exit (实心)
  static const IconData fullscreenExit = IconData(0xE756, fontFamily: _family);

  /// favorite (实心)
  static const IconData heart = IconData(0xE75A, fontFamily: _family);

  /// history / history_toggle_off (实心)
  static const IconData history = IconData(0xE75E, fontFamily: _family);

  /// home (实心)
  static const IconData home = IconData(0xE760, fontFamily: _family);

  /// energy_savings_leaf (实心)
  static const IconData leaf = IconData(0xE764, fontFamily: _family);

  /// chevron_left (实心)
  static const IconData leftSmall = IconData(0xE766, fontFamily: _family);

  /// line_weight (实心)
  static const IconData lineHeight = IconData(0xE767, fontFamily: _family);

  /// link (实心)
  static const IconData link = IconData(0xE768, fontFamily: _family);

  /// checklist (实心)
  static const IconData listCheck2 = IconData(0xE769, fontFamily: _family);

  /// auto_fix_normal (实心)
  static const IconData magic2 = IconData(0xE76C, fontFamily: _family);

  /// auto_fix_high (实心)
  static const IconData magic3 = IconData(0xE76E, fontFamily: _family);

  /// menu_open / menu_rounded (实心)
  static const IconData menu = IconData(0xE771, fontFamily: _family);

  /// mic_external_on (实心)
  static const IconData mic = IconData(0xE774, fontFamily: _family);

  /// (extra:miniplayer) (实心)
  static const IconData miniplayer = IconData(0xE776, fontFamily: _family);

  /// nights_stay (实心)
  static const IconData moonStars = IconData(0xE77A, fontFamily: _family);

  /// select_all (实心)
  static const IconData multiselect = IconData(0xE77C, fontFamily: _family);

  /// music_note (实心)
  static const IconData music = IconData(0xE77D, fontFamily: _family);

  /// library_music (实心)
  static const IconData music2 = IconData(0xE77E, fontFamily: _family);

  /// pause / pause_rounded (实心)
  static const IconData pause = IconData(0xE784, fontFamily: _family);

  /// pause_circle_filled (实心)
  static const IconData pauseCircle = IconData(0xE785, fontFamily: _family);

  /// offline_pin (实心)
  static const IconData pin = IconData(0xE78A, fontFamily: _family);

  /// play_arrow / play_arrow_rounded (实心)
  static const IconData play = IconData(0xE78C, fontFamily: _family);

  /// play_circle_filled (实心)
  static const IconData playCircle = IconData(0xE78D, fontFamily: _family);

  /// playlist_play / queue_music (实心)
  static const IconData playlist = IconData(0xE78F, fontFamily: _family);

  /// qr_code_2 (实心)
  static const IconData qrcode = IconData(0xE794, fontFamily: _family);

  /// autorenew / refresh / sync (实心)
  static const IconData refresh = IconData(0xE795, fontFamily: _family);

  /// restart_alt (实心)
  static const IconData refreshAnticlockwise = IconData(0xE796, fontFamily: _family);

  /// repeat (实心)
  static const IconData repeat = IconData(0xE798, fontFamily: _family);

  /// repeat_one (实心)
  static const IconData repeatOne = IconData(0xE799, fontFamily: _family);

  /// chevron_right (实心)
  static const IconData rightSmall = IconData(0xE79A, fontFamily: _family);

  /// hourglass_top (实心)
  static const IconData sandglass = IconData(0xE79D, fontFamily: _family);

  /// search (实心)
  static const IconData search2 = IconData(0xE79E, fontFamily: _family);

  /// search_off (实心)
  static const IconData search2None = IconData(0xE79F, fontFamily: _family);

  /// manage_search (实心)
  static const IconData search3 = IconData(0xE7A0, fontFamily: _family);

  /// send (实心)
  static const IconData sendPlane = IconData(0xE7A2, fontFamily: _family);

  /// dns (实心)
  static const IconData server = IconData(0xE7A3, fontFamily: _family);

  /// shuffle (实心)
  static const IconData shuffle = IconData(0xE7A8, fontFamily: _family);

  /// skip_next (实心)
  static const IconData skipForward = IconData(0xE7AA, fontFamily: _family);

  /// skip_previous (实心)
  static const IconData skipPrevious = IconData(0xE7AC, fontFamily: _family);

  /// ac_unit (实心)
  static const IconData snowflake = IconData(0xE7AD, fontFamily: _family);

  /// graphic_eq (实心)
  static const IconData soundLine = IconData(0xE7AE, fontFamily: _family);

  /// space_bar (实心)
  static const IconData space = IconData(0xE7B0, fontFamily: _family);

  /// speaker (实心)
  static const IconData speaker = IconData(0xE7B1, fontFamily: _family);

  /// crop_square (实心)
  static const IconData square = IconData(0xE7B3, fontFamily: _family);

  /// star (实心)
  static const IconData star = IconData(0xE7B4, fontFamily: _family);

  /// stop (实心)
  static const IconData stop = IconData(0xE7B6, fontFamily: _family);

  /// subtitles (实心)
  static const IconData subtitle = IconData(0xE7BA, fontFamily: _family);

  /// wb_sunny (实心)
  static const IconData sun = IconData(0xE7BC, fontFamily: _family);

  /// thunderstorm (实心)
  static const IconData thunderstorm = IconData(0xE7BF, fontFamily: _family);

  /// transform_rounded (实心)
  static const IconData transfer = IconData(0xE7C2, fontFamily: _family);

  /// swap_horiz (实心)
  static const IconData transferHorizontal = IconData(0xE7C3, fontFamily: _family);

  /// translate (实心)
  static const IconData translate = IconData(0xE7C5, fontFamily: _family);

  /// link_off (实心)
  static const IconData unlink = IconData(0xE7C7, fontFamily: _family);

  /// keyboard_arrow_up (实心)
  static const IconData upSmall = IconData(0xE7CA, fontFamily: _family);

  /// person (实心)
  static const IconData user = IconData(0xE7CB, fontFamily: _family);

  /// volume_up (实心)
  static const IconData volume = IconData(0xE7CD, fontFamily: _family);

  /// volume_down (实心)
  static const IconData volumeMute = IconData(0xE7CE, fontFamily: _family);

  /// volume_off (实心)
  static const IconData volumeOff = IconData(0xE7CF, fontFamily: _family);

  /// warning_amber_rounded (实心)
  static const IconData warning = IconData(0xE7D1, fontFamily: _family);

  /// wifi_tethering (实心)
  static const IconData wifi = IconData(0xE7D4, fontFamily: _family);

}
