// ArchoeraMusic UI
// Copyright (C) 2026 Archoera && BetaStudio2
// SPDX-License-Identifier: AGPL-3.0-or-later

//! 构建脚本：从 Flutter 的 ARB 文案中抽取 `mcpShell*` 字符串，生成一份 Rust
//! 常量表（`help_strings.rs`）。原生 CLI 因此复用与 Dart 端**同一份**本地化
//! 文案，避免两套帮助文本漂移。
//!
//! 生成的 `STRINGS` 为 `(locale, key, value)` 三元组；locale 取自文件名
//! `app_<locale>.arb` → `<locale>`。

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let l10n_dir = PathBuf::from(&manifest).join("../../lib/l10n");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_file = out_dir.join("help_strings.rs");

    println!("cargo:rerun-if-changed=build.rs");
    if l10n_dir.is_dir() {
        println!("cargo:rerun-if-changed={}", l10n_dir.display());
    }

    let mut entries: Vec<(String, String, String)> = Vec::new();
    let mut files: Vec<PathBuf> = Vec::new();
    if let Ok(read) = fs::read_dir(&l10n_dir) {
        for e in read.flatten() {
            let name = e.file_name().to_string_lossy().to_string();
            if name.starts_with("app_") && name.ends_with(".arb") {
                files.push(e.path());
            }
        }
    }
    files.sort();

    for path in &files {
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        let code = name
            .trim_start_matches("app_")
            .trim_end_matches(".arb")
            .to_string();
        let Ok(text) = fs::read_to_string(path) else {
            continue;
        };
        let Ok(json) = serde_json::from_str::<serde_json::Value>(&text) else {
            continue;
        };
        let Some(obj) = json.as_object() else { continue };
        for (key, value) in obj {
            if !key.starts_with("mcpShell") {
                continue;
            }
            if let Some(s) = value.as_str() {
                entries.push((code.clone(), key.clone(), s.to_string()));
            }
        }
    }

    let mut src = String::from("// @generated by build.rs —— 勿手改\n");
    src.push_str("pub static STRINGS: &[(&str, &str, &str)] = &[\n");
    for (code, key, value) in &entries {
        // Debug 格式化输出合法的 Rust 字符串字面量（自动转义）。
        src.push_str(&format!("    ({code:?}, {key:?}, {value:?}),\n"));
    }
    src.push_str("];\n");

    fs::write(&out_file, src).expect("write help_strings.rs");
}
