// AUTO-GENERATED by app/eta-tools/eta_mark — 品牌标识字形（EtaMark 独立字体族）。
// 承载品牌标识（源图黑白矢量化），供 AppLogo / 启动页等品牌位置使用。
// 字体文件：assets/fonts/EtaMark.ttf
import 'package:flutter/widgets.dart';

/// 品牌标识字形（eta.mark 体系，与通用图标 EtaIcons 解耦）。
abstract final class EtaMark {
  static const String _family = 'EtaMark';

  /// 均衡器频谱标识（AppLogo 中央图形）。
  static const IconData brand = IconData(0xE101, fontFamily: _family);

  /// EraSync 标识（圆角方 + 负形波形，自研内核 EraAudioSync 品牌）。
  static const IconData erasync = IconData(0xE102, fontFamily: _family);

  EtaMark._();
}
