// AUTO-GENERATED by app/eta-tools/eta_mark — 品牌标识字形（EtaMark 独立字体族）。
// 承载「均衡器频谱」品牌标识（源：logo-trim.png 黑白矢量化），供 AppLogo 等品牌位置使用。
// 字体文件：assets/fonts/EtaMark.ttf
import 'package:flutter/widgets.dart';

/// 品牌标识字形（eta.mark 体系，与通用图标 EtaIcons 解耦）。
abstract final class EtaMark {
  static const String _family = 'EtaMark';

  /// 均衡器频谱标识（AppLogo 中央图形）。
  static const IconData brand = IconData(0xE101, fontFamily: _family);

  EtaMark._();
}
